### ISSUE TITLE
Typo in the manual

### ISSUE THREAD

**Issue by mscook** [katholt/RedDog#33]
Can you point me to BAMTools v1.1? I think this is related to #31

**Comment by d-j-e** [comment]
It is related to #31 - bamtools is no longer required by RedDog and this dependency needs to be removed from the manual. bamtools is still active and up to version 2.3 atm...

**Comment by mscook** [comment]
Hi David,

While it's not needed any longer, I actually can't find bamtools 1.*

1.* is referenced in earlier homebrew formula & the download links work -
https://github.com/Homebrew/homebrew-science/commits/master/bamtools.rb

However no releases exist before 2.0*. Perhaps he deleted all the old ones.

(https://github.com/pezmaster31/bamtools/releases)

**Just to clarify, are bcftools needed (and vcftools) need by Reddog?**

**Comment by d-j-e** [comment]
Hi Mitch,
That may well be the case - glad I changes from it to eautils...
bcftools and vcftools used to be packaged into the Samtools package, but since version 1.0 you need to install them separately - and yes, RedDog needs them...
