### ISSUE TITLE
Adding links in the table of contents and adding bookmarks in the manual and tutorial

### ISSUE THREAD

**Issue by wanyuac** [katholt/RedDog#38]
Currently we cannot jump to a content page directly from the table of content, and there are no bookmarks provided in the PDF. This problem can be solved by adding headings to the document and exporting it as a PDF in MS Word.

**Comment by d-j-e** [comment]
Use the wiki for now - you can jump from the toc in that - and its searchable (I think)

**Comment by wanyuac** [comment]
A solution is no longer needed.
