### ISSUE TITLE
account settings

### ISSUE THREAD

**Issue by jasonshiller** [katholt/RedDog#41]
Hi,

I am trying to run RedDog on the cluster at VLSCI. I need to specify a particular account
e.g. #SBATCH --account=VR000.. to use the quota of my group (my default account doesn't have quota). Is there a way to specify which account the pipeline uses? 

Cheers,
Jason

**Comment by d-j-e** [comment]
Hi Jason,
Not atm - but have contacted one of the authors of Rubra to see if it can be added as an option...
cheers,
David

**Comment by jasonshiller** [comment]
Thanks David
