### ISSUE TITLE
 Failed to run 'python checkBam.py.....BAM too small: deleted

### ISSUE THREAD

**Issue by SabeenR** [katholt/RedDog#54]
Hi David,
I'm having a different issue now. Not sure what changed in the system.  I wanted to re-run the test dataset from start to finish just to make sure it all runs correctly.

When I ran it, this was the output:
+++++++++++++++++
Start Pipeline? (y/n) y

Starting pipeline...
93 jobs to be executed in total
86 jobs left to execute
Error: command failed: python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019786/ERR019786.bam PE /root/Documents/RedDog_test_input/ERR019786_1.fastq.gz
Error: command failed: python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019793/ERR019793.bam PE /root/Documents/RedDog_test_input/ERR019793_1.fastq.gz
Error: command failed: python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019794/ERR019794.bam PE /root/Documents/RedDog_test_input/ERR019794_1.fastq.gz
Traceback (most recent call last):
  File "/bin/rubra", line 11, in <module>
    load_entry_point('Rubra==0.1.5', 'console_scripts', 'rubra')()
  File "build/bdist.linux-x86_64/egg/rubra/rubra.py", line 66, in main
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2671, in pipeline_run
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2406, in fill_queue_with_job_parameters
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2345, in parameter_generator
ruffus.ruffus_exceptions.RethrownJobError: 
    
    Exceptions generating parameters for
    
    'def RedDog.indexBam(...):'
    
    Original exception:
    
    Exception #1
    ruffus.ruffus_exceptions.MissingInputFileError(    
        
        
        No way to run job: Input file ['/root/Documents/RedDog_test1_output/temp/ERR019786/ERR019786.bam'] does not exist):
    for RedDog.indexBam.
    
    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2279, in parameter_generator
        check_input_files_exist (*param)
      File "build/bdist.linux-x86_64/egg/ruffus/file_name_parameters.py", line 191, in check_input_files_exist
        "Input file ['%s'] does not exist" % f)
    MissingInputFileError:     
        
        
        No way to run job: Input file ['/root/Documents/RedDog_test1_output/temp/ERR019786/ERR019786.bam'] does not exist
+++++++++++++++++

SO then I ran the individual bowtie command:
++++++++++++++
bowtie2 --sensitive-local -x /root/Documents/RedDog_test1_output/temp/ref_ALL -1 /root/Documents/RedDog_test_input/ERR019786_1.fastq.gz -2 /root/Documents/RedDog_test_input/ERR019786_2.fastq.gz -X 2000 | samtools view -ubS - | samtools sort - -o /root/Documents/RedDog_test1_output/temp/ERR019786/ERR019786.bam
++++++++++++++

this was the output:  (ERR): bowtie2-align died with signal 11 (SEGV) (core dumped)

This is the first part of the log:
******************logBegin***
- makeDir: python makeDir.py /root/Documents/RedDog_test1_output/ ERR019786,ERR019794,ERR019793,
- makeRef: python convertGenbankToFasta.py /root/Documents/RedDog_test_input/ref_ALL.gbk /root/Documents/RedDog_test1_output/temp/ref_ALL.fasta

- indexRef: samtools faidx /root/Documents/RedDog_test1_output/temp/ref_ALL.fasta

- buildBowtieIndex: bowtie2-build /root/Documents/RedDog_test1_output/temp/ref_ALL.fasta /root/Documents/RedDog_test1_output/temp/ref_ALL

- alignBowtiePE: bowtie2 --sensitive-local -x /root/Documents/RedDog_test1_output/temp/ref_ALL -1 /root/Documents/RedDog_test_input/ERR019786_1.fastq.gz -2 /root/Documents/RedDog_test_input/ERR019786_2.fastq.gz -X 2000 | samtools view -ubS - | samtools sort - -o /root/Documents/RedDog_test1_output/temp/ERR019786/ERR019786.bam

 - alignBowtiePE: bowtie2 --sensitive-local -x /root/Documents/RedDog_test1_output/temp/ref_ALL -1 /root/Documents/RedDog_test_input/ERR019794_1.fastq.gz -2 /root/Documents/RedDog_test_input/ERR019794_2.fastq.gz -X 2000 | samtools view -ubS - | samtools sort - -o /root/Documents/RedDog_test1_output/temp/ERR019794/ERR019794.bam

- alignBowtiePE: bowtie2 --sensitive-local -x /root/Documents/RedDog_test1_output/temp/ref_ALL -1 /root/Documents/RedDog_test_input/ERR019793_1.fastq.gz -2 /root/Documents/RedDog_test_input/ERR019793_2.fastq.gz -X 2000 | samtools view -ubS - | samtools sort - -o /root/Documents/RedDog_test1_output/temp/ERR019793/ERR019793.bam

- checkBam: python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019786/ERR019786.bam PE /root/Documents/RedDog_test_input/ERR019786_1.fastq.gz

- Failed to run 'python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019786/ERR019786.bam PE /root/Documents/RedDog_test_input/ERR019786_1.fastq.gz'
BAM too small: deleted
Non-zero exit status 1

- checkBam: python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019793/ERR019793.bam PE /root/Documents/RedDog_test_input/ERR019793_1.fastq.gz

- checkBam: python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019794/ERR019794.bam PE /root/Documents/RedDog_test_input/ERR019794_1.fastq.gz

- Failed to run 'python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019793/ERR019793.bam PE /root/Documents/RedDog_test_input/ERR019793_1.fastq.gz'
BAM too small: deleted
Non-zero exit status 1

- Failed to run 'python checkBam.py /root/Documents/RedDog_test1_output/temp/ERR019794/ERR019794.bam PE /root/Documents/RedDog_test_input/ERR019794_1.fastq.gz'
BAM too small: deleted
Non-zero exit status 1
***************Truncated_log_end**********

**Comment by d-j-e** [comment]
Hi Sabeen, apologies for not getting back quicker, have been on holiday.

Have you moved the test reads since last using them? There is a small possibility that they got corrupted. (You could download them again to test this)
Otherwise, can you send me the config file for the run? 
What is the operating system?
Also, make sure you have the latest version of bowtie2, especially if you are using Ubuntu as the OS.

regards,
David

**Comment by SabeenR** [comment]
Thank you David,
I re-dowloaded the test dataset and ran it again and it ran all the way through.
I'll go ahead and close this.

Sabeen
