### ISSUE TITLE
Use of parseSNPtable.py 

### ISSUE THREAD

**Issue by MostafaYA** [katholt/RedDog#56]
Hi, 
I beleive that it is possible to run the script `parseSNPtable.py` on any snp table produced not necessarily by reddog. Am I right?
If this is right, how we could generate the table from an alignment file like that produced by parSNP (including reference) or as mentioned in the post processing steps of reddog, after masking the recombination sites. 
 
The pupose is to get benefit from the script other functionalities like coding, cons etc

Thanks,

**Comment by d-j-e** [comment]
Yes it is possible to run the script on any SNP table, though there are some expectations... 

The file should be comma-delimitated, with the isolate names in the first row, beginning with 'Pos, iso_A...' where  'iso_A' is your first isolate. each SNP should begin with the position in the reference...

Example table:
Pos,iso_A,iso_B,iso_C
23,A,G,C
254,T,T,C
1111,A,G,A

I'm not sure of the format of the parSNP program, but it can't be hard to manipulate it to conform...

cheers,
David

**Comment by MostafaYA** [comment]
Thanks a lot
