### ISSUE TITLE
Issue with plotTree R code

### ISSUE THREAD

**Issue by spencer411** [katholt/RedDog#59]
I am running my own dataset through the RedDog pipeline, and have been using the tutorial as a guide. I have been able to get through everything, including the post-processing, but am stuck on what seems to be a simple line of R code for the tree plotting portion at the very end of the tutorial. I have a .nxs tree of bacterial genomes with two plasmids (plasmid_cover.csv). When I attempt to run the code provided in the tutorial modified for my dataset I get the following error message (w/traceback). It seems like there should be a simple enough fix, but I can't figure the code. I am pretty basic when it comes to coding in R, so any help with this final step is greatly, greatly appreciated.

> source('plotTree.R');
> library('ape');
> plotTree(tree='Final_Tree.nxs', infoFile='metadata.csv', outputPDF='Tree_figure.pdf', tipColours=c('red','black'), legend=T, legend.pos='bottomleft', colourNodesBy="Group", tip.colour.cex=1.2, heatmap.colours=colorRampPalette(c('orange','blue'), space='rgb')(100), heatmapData='plasmid_cover.csv',treeWidth=50, infoWidth=0.001, dataWidth=50, tip.labels = T, tipLabelSize = 0.7, offset=0.03, colLabelCex=0.001)

 Error in if (all(phy$node.label == "")) phy$node.label <- NULL : 
  missing value where TRUE/FALSE needed

Traceback: 
4.
FUN(X[[i]], ...) 
3.
lapply(STRING[nocolon], .cladoBuild) 
2.
read.tree(tree) at plotTree.R#77
1.
plotTree(tree = "Final_Tree.nxs", infoFile = "metadata.csv", 
    outputPDF = "anthrax_figure.pdf", tipColours = c("red", "black"), 
    legend = T, legend.pos = "bottomleft", colourNodesBy = "Group", 
    tip.colour.cex = 1.2, heatmap.colours = colorRampPalette(c("orange",  ...

**Comment by d-j-e** [comment]
Can u send me the final_tree.nxs? - something in that is screwing up the script. I didn't write this bit of code, so can't debug it easily.

**Comment by spencer411** [comment]
Two files attached. I thought this might have been a problem with not including bootstrap node values, so I created the file twice, but using either one I get the same error message. The bootstrap values are not important, given that it is just FastTree, but so you have both... Note that I used the .txt extension here because GitHub won't allow me to upload .nxs files. Thank you for the speedy reply.
[Final_Tree_w_nodes.txt](https://github.com/katholt/RedDog/files/2493846/Final_Tree_w_nodes.txt)
[Final_Tree.txt](https://github.com/katholt/RedDog/files/2493847/Final_Tree.txt)

**Comment by d-j-e** [comment]
I can't see anything wrong with the tree, so am going to try a different approach

Attached are the tree, cover file and metadata from the tutorial - can you try plot them?

[2011C-3493_final.nxs.txt](https://github.com/katholt/RedDog/files/2493950/2011C-3493_final.nxs.txt)
[metadata.csv.txt](https://github.com/katholt/RedDog/files/2493951/metadata.csv.txt)
[output_test.csv.txt](https://github.com/katholt/RedDog/files/2493952/output_test.csv.txt)

**Comment by kelwyres** [comment]
Looks like your tree is in nexus format? plotTree.R is expecting the tree in newick format - so that is likely the source of the error. You should be able to convert the format in figtree or dendroscope or other tree viewing programs, or you could try using the read.nexus function in the ape R package to save the tree as a phylo object then give this to the plotTree script.
e.g. try something like this
tr <- read.nexus('path_to_tree_file')
plotTree(tree =  tr, ... other arguments....)

**Comment by spencer411** [comment]
Thank you all!

It worked with the tree in newick format. I could not get it to work with the tutorial materials provided here, or using my own tree in nexus format (I got the same error message for both).

Just a note on a couple of other inconsistencies in the tutorial for anyone else having problems...

On page 27 when creating the plasmid coverage file, the tutorial references the GeneSummary.csv file, but you actually need the CoverMatrix.csv file to create the plasmid_cover.csv.

Also note that the metadata file should have three rows with the headings: Isolate; Group; Name to work correctly with the final tree plotting (the data provided in the tutorial only has one heading; Group).

Great pipeline, thanks a million!
