### ISSUE TITLE
Should the read data be preprocessed before running RedDog?

### ISSUE THREAD

**Issue by quocviet0908** [katholt/RedDog#66]
Hi,
I'm currently trying to used RedDog to run real sequenced data. However, I wonder if I should process the raw data with QC software before actual running of the pipeline? From inspecting the config file and the flow chart the pipeline starts right on the mapping read step and goes down further without mentioning about QC step (even in the tutorial file).

I appreciate any guidance (I'm still new to this field).

Thanks.

**Comment by d-j-e** [comment]
No, though you can run them through fastqc to make sure there are reads to map. The 'sensitive local' setting means the reads are soft clipped at both ends, so adapters aren't an issue. And reddog does qc the mapped data, failing any read set that doesn't have enough coverage (either low depth or low coverage across the mapped genome...).

If you want to use the same reads for assembly, then you will need to remove adapters.
