### ISSUE TITLE
Outputting a fasta with invariant and variant sites

### ISSUE THREAD

**Issue by AdrianAllen1977** [katholt/RedDog#73]
Hi, have used RedDog to do SNP calling for clonal organisms (have found it very useful, thanks) but am now wanting to look at species that undergo recombination. Was planning to investigate recombination with ClonalFrameML or Gubbins, but need a complete alignment file of variant and invariant sites.  Can I change the RedDog configuration file to output a fasta alignment for all sites to facilitate this?

Thanks

**Comment by kelwyres** [comment]
Hi Adrian, 
We have a work-around for this very use-case- we use the attached python script to generate a pseudo-whole-genome alignment from the RedDog allele matrix. It takes as input the original reference sequence in fasta format (same reference that was used for RedDog) and the snp allele matrix. It will make an alignment in fasta format where the invariant sites are filled to match the reference alleles and the variant sites are filled with the information in your allele matrix. Note that this means only the sites in the matrix will be variable in your output alignment, so if you use the 95% core allele matrix you will be effectively masking any variation at non-core sites.
Hope this makes sense, but feel free to ask questions.
Kelly 
[snpTable2GenomeAlignment.py.zip](https://github.com/katholt/RedDog/files/5968810/snpTable2GenomeAlignment.py.zip)

**Comment by AdrianAllen1977** [comment]
Dear Kelly,
Thank you so very much for this. Very kind of you to put that together,
and  most unexpected on my part.
Thank you again for your expertise and helpfulness, will look forward to
having a go with this script.
Very best
Adrian

**Comment by AdrianAllen1977** [comment]
Hi Kelly, sorry to bother you again, I'm not a python user by any stretch, can you give me an idea pointers on the script I need to use in terminal to get this running?  Presumably in the command line I'll need to define the path for the csv file and the reference fasta?
Sorry for the hassle and thanks again.
Adrian

**Comment by kelwyres** [comment]
Hi Adrian, 

No problem, here is an example: 
`python3 snpTable2GenomeAlignment.py -r insert_path_to_reference_sequence.fasta -s insert_path_to_allele_matrix.csv > name_of_output_file.fasta`

This assumes;
i) that you are woking in the directory where the python script is saved- if not just replace the name of the script with its full path
ii) the reference sequence file is the same as the one you used for Reddog (full length i.e. not a subsequence)

Kelly

**Comment by AdrianAllen1977** [comment]
Thanks again, Kelly.  Much appreciated!  This might end up being in a
protocol of ours at some point, how shoudl I credit you guys for this?
Just reference it as part of the RedDog package and the Holt lab?

Thank you

Adrian

**Comment by kelwyres** [comment]
Hi, 

Yes you can just cite this github repo- the script is included here (just updated to the python3, which is what I attached above).

Thanks,
Kelly
